### ISSUE TITLE
Upgrade plugin to work with NopCommerce 3.8

### ISSUE THREAD

**Issue by fr-ench** [tomvanenckevort/NopCommerce.HTMLOptimiser#7]
Are there any plans to upgrade the plugin for the newer version of NopCommerce? Current version of plugin doesn't seem to work with NopCommerce 3.8.

Can you please tell me if I'm doing smth wrong or should some changes be made to the plugin? Thank you!

**Comment by tomvanenckevort** [comment]
No, this plugin is not compatible with NopCommerce 3.8 and unfortunately won't be upgraded by me, since I no longer work with NopCommerce.
However, the source code is available to anyone to fork and update to work with NopCommerce 3.8.
